"""empty message

Revision ID: 26115a587012
Revises: 
Create Date: 2020-03-17 20:15:52.799889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26115a587012'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_email'), 'subscription', ['email'], unique=True)
    op.create_table('subscription_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_hours')
    op.drop_index(op.f('ix_subscription_email'), table_name='subscription')
    op.drop_table('subscription')
    # ### end Alembic commands ###
